- name: ec2 and r53
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-090908868bc302a71
    zone_id: Z01508593JUYY9SHIBG2D
    domain_name: mallikharjundevops.fun
    
    # we can pass instances through command line by using -e (refer the command below)
    # ansible-playbook -i inventory.ini ec2_r53_playbook.yaml -e "instances=['instance1', 'instance2', 'instance3']"

    # instances:
    # - mongodb
    # - redis
    # - mysql
    # - rabbitmq
    # - catalogue
    # - user
    # - cart
    # - shipping
    # - payment
    # - frontend
    
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      state: present
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
    
  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"
    
  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mallikharjundevops.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  # we are creating one record with public only for frontend
  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" # mallikharjundevops.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"